kony = kony || {};
kony.adminConsole = kony.adminConsole || {};
kony.adminConsole.loans = kony.adminConsole.loans || {};

kony.adminConsole.loans.fieldsToVAlidate = {
  "LoanInfo": {
    "rbgResponseCoApplicant":{
      "normalSkin": "sknRbgCoApplicantKA",
      "skin": "sknRbgError",
      "errorLabel": "lblCoApplicantError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"radio",
      "reviewKey":"lblSummaryApplicationTypeValue",
      "isDatavalidated": true,
    },
    "txtAmount": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblLoanAmountError",
      "errorMessageMandatory": "Enter Loan Amount",
      "errorMessageValid": "Enter Loan Amount in given range",
      "parentComp":"loanAmountBox",
	  "isMandatory": true,
      "isValidated": null,
      "isDatavalidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryAmountRequestedValue",
      "minAmount": 1000,
      "maxAmount": 50000
    },
    "listBoxPurposeCollateral": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblPurposeError",
      "errorMessageMandatory": "Select Loan Purpose",
      "errorMessageValid": "Select Loan Purpose",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
       "reviewKey":"lblSummaryPurposeValue",
      "isDatavalidated": true
    },
    "listBoxLoanTerm" : {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblLoanTermError",
      "errorMessageMandatory": "Select Loan Term",
      "errorMessageValid": "Select Loan Term",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryLoanTerms",
      "isDatavalidated": true
    }
  },
  "PersonalInfo": {
    "txtName": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblFirstNameError",
      "errorMessageMandatory": "Enter First Name",
      "errorMessageValid": "Enter valid First Name",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryFirstNameValue",
      "isDatavalidated": null
    },
    "txtMiddleName": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblMiddleNameError",
      "errorMessageMandatory": "Enter Middle Name",
      "errorMessageValid": "Enter valid Middle Name",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryMiddleNameValue",
      "isDatavalidated": null
    },
	"txtLastName": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblLastNameError",
      "errorMessageMandatory": "Enter Last Name",
      "errorMessageValid": "Enter valid Last Name",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryLastNameValue",
      "isDatavalidated": null
    },
    "txtEmailAddress": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblEmailAddressError",
      "errorMessageMandatory": "Enter Email address",
      "errorMessageValid": "Enter valid Email address",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryEmailValue",
      "isDatavalidated": null
    },  
    "txtSSN": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblSSNError",
      "errorMessageMandatory": "Enter SSN",
      "errorMessageValid": "Enter valid SSN",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummarySSNValue",
      "isDatavalidated": null
    },
    "txtDLNumber": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblDLNumberError",
      "errorMessageMandatory": "Enter License Number",
      "errorMessageValid": "Enter valid License Number",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryDriversLicenseValue",
      "isDatavalidated": null
    },
    "txtHomePhoneNumber": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblHomePhoneError",
      "errorMessageMandatory": "Enter Phone Number",
      "errorMessageValid": "Enter valid Phone Number",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryHomePhoneValue",
      "isDatavalidated": null
    },
    "txtCellPhone": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblCellPhoneError",
      "errorMessageMandatory": "Enter Phone Number",
      "errorMessageValid": "Enter valid Phone Number",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCellPhoneValue",
      "isDatavalidated": null
    },
    "txtBusinessPhone": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblBusinessPhoneError",
      "errorMessageMandatory": "Enter Phone Number",
      "errorMessageValid": "Enter valid Phone Number",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryBusinessPhoneValue",
      "isDatavalidated": null
    },
    "txtAddressLine1": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblCurrentAddressError",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
	  "parentComp":"AddressComponent",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryPersonalInfoAddressLine1Value",
      "isDatavalidated": true
    },
    "txtAddressLine2": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblAddressLine2Error",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
	  "parentComp":"AddressComponent",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryPersonalInfoAddressLine2Value",
      "isDatavalidated": null
    },
    "lstAddress1Country": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCurrentCountryError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "parentComp":"AddressComponent",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryCountryValue",
      "isDatavalidated": true
    },
    "lstAddress1State": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCurrentStateError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "parentComp":"AddressComponent",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryPersonalInfoStateValue",
      "isDatavalidated": true
    },
    "txtAddress1City": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCurrentCityError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "parentComp":"AddressComponent",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryPersonalInfoCityValue",
      "isDatavalidated": null
    },
    "txtAddress1ZipCode": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblCurrentZipCodeError",
      "errorMessageMandatory": "Enter ZIP Code",
      "errorMessageValid": "Enter valid ZIP Code",
	  "parentComp":"AddressComponent",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryZipCodeValue",
      "isDatavalidated": null
    },
    "lstAddress1OccupyingPlace": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblOccupyingPlaceError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryHousingValue",
      "isDatavalidated": true
    },
    "rbgYears": {
      "normalSkin": "sknRbgCoApplicantKA",
      "skin": "sknRbgError",
      "errorLabel": "lblYearsError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "isMandatory": true,
      "isValidated": null,
      "widgetType":"radio",
      "reviewKey":"lblReviewYearsAndMonthSpentValue",
      "isDatavalidated": true
    },
    "txtAddressLine1Previous": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPrevAddressLine1Error",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryPrevPersonalInfoAddressLine1Value",
      "isDatavalidated": null
    },
    "txtAddressLine2Previous": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPrevAddressLine2Error",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryPrevPersonalInfoAddressLine2Value",
      "isDatavalidated": null
    },
    "lstCountryPrevious": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCurrentCountryError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "reviewKey":"lblSummaryPrevCountry",
      "isDatavalidated": true
    },
    "lstAddressStatePrevious": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCurrentStateError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "reviewKey":"lblSummaryPrevPersonalInfoStateValue",
      "isDatavalidated": true
    },
    "txtAddressCityPrevious": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblPrevCityError",
      "errorMessageMandatory": "Enter city",
      "errorMessageValid": "Enter valid city",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryPrevPersonalInfoCityValue",
      "isDatavalidated": null
    },  
    "txtAddressZipCodePrevious": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPrevZipCodeError",
      "errorMessageMandatory": "Enter ZIP Code",
      "errorMessageValid": "Enter valid ZIP Code",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryPrevZipCodeValue",
      "isDatavalidated": null
    },
    "lstAddressOccupyingPrevious": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblOccupyingPlaceError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
	  "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "reviewKey":"lblSummaryPrevHousingValue",
      "isDatavalidated": true
    },
  },
  "IncomeInfo":{
	"txtHousingRent": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblHousingRentError",
      "errorMessageMandatory": "Enter valid Rent",
      "errorMessageValid": "Enter valid Rent",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"lstEmploymentBasedIncome": {
	  "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblEmploymentError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"list",
      "isDatavalidated": true
	},
    "txtNameOfTheEmployer": {
	  "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblEmploymentNameError",
      "errorMessageMandatory": "Employer name cannot be empty",
      "errorMessageValid": "Enter valid Employer name",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPresentTitleGrade": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblDesignationError",
      "errorMessageMandatory": "Enter valid Data",
      "errorMessageValid": "Enter valid Data",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtBussinessName": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblBusinessNameError",
      "errorMessageMandatory": "Name can't be empty",
      "errorMessageValid": "Enter valid name",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPresentMonthlySalary": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblGrossIncomeError",
      "errorMessageMandatory": "Income can't be empty",
      "errorMessageValid": "Enter valid Income",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"lstPeriod": {
	  "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lstPeriodError",
      "errorMessageMandatory": "Pay period cannot be empty",
      "errorMessageValid": "Enter valid pay period",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"list",
      "isDatavalidated": true
	},
	"txtPresentEmployerAddressLine1": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblEmploymentAddressError",
      "errorMessageMandatory": "Address cannot be empty",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPresentEmployerAddressLine2": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPresentAddressLine2Error",
      "errorMessageMandatory": "Address cannot be empty",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"listPresentEmploymentCountry": {
	  "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblEmploymentCountryError",
      "errorMessageMandatory": "Country cannot be empty",
      "errorMessageValid": "Country cannot be empty",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"list",
      "isDatavalidated": true
	},
	"listPresentEmployeeState": {
	  "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblEmploymentStateError",
      "errorMessageMandatory": "State cannot be empty",
      "errorMessageValid": "State cannot be empty",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"list",
      "isDatavalidated": true
	},
	"txtPresentEmploymentCity": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblEmploymentCityEror",
      "errorMessageMandatory": "City cannot be empty",
      "errorMessageValid": "Enter valid City",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPresentZipCode": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblEmploymentZipError",
      "errorMessageMandatory": "Zipcode cannot be empty",
      "errorMessageValid": "Enter valid Zipcode",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"tbxPreviousEmployerName": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousEmployerError",
      "errorMessageMandatory": "Employer Name cannot be empty",
      "errorMessageValid": "Enter valid Employer Name",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPreviousDesignation": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousDesignationError",
      "errorMessageMandatory": "Title cannot be empty",
      "errorMessageValid": "Enter valid Title",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPreviousIncome": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousIncomeError",
      "errorMessageMandatory": "Income cannot be empty",
      "errorMessageValid": "Enter valid Income",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"lstPreviousPayPeriod": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousPayPeriodError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "isDatavalidated": null
	},
	"txtPreviousAddressOne": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousAddressOneError",
      "errorMessageMandatory": "Address cannot be empty",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPreviousAddressTwo": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviuosAddressLineTwoError",
      "errorMessageMandatory": "Address cannot be empty",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"lstPreviousCountry": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviuosCountryError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "isDatavalidated": null
	},
	"lstPreviousState": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousStateError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"list",
      "isDatavalidated": null
	},
	"txtPreviousCity": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousCityError",
      "errorMessageMandatory": "City cannot be empty",
      "errorMessageValid": "Enter valid City",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	},
	"txtPreviousZipCode": {
	  "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPreviousZipCodeError",
      "errorMessageMandatory": "Zipcode cannot be empty",
      "errorMessageValid": "Enter valid Zipcode",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "isDatavalidated": null
	}
  },
  "CoApplicantPersonalInfo": {
    "txtNameCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblFirstNameCoAError",
      "errorMessageMandatory": "Enter First Name",
      "errorMessageValid": "Enter valid First Name",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppFirstNameValue",
      "isDatavalidated": null
    },
	"txtMiddleNameCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblMiddleNameCoAError",
      "errorMessageMandatory": "Enter Middle Name",
      "errorMessageValid": "Enter valid Middle Name",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppMiddleNameValue",
      "isDatavalidated": null
    },
    "txtLastNameCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblLastNameCoAError",
      "errorMessageMandatory": "Enter Last Name",
      "errorMessageValid": "Enter valid Last Name",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppLastNameValue",
      "isDatavalidated": null
    },
    "txtEmailAddressCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblEmailCoAError",
      "errorMessageMandatory": "Enter Email address",
      "errorMessageValid": "Enter valid Email address",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppEmailValue",
      "isDatavalidated": null
    },
    "txtSSNCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblSSNCoAError",
      "errorMessageMandatory": "Enter SSN",
      "errorMessageValid": "Enter valid SSN",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppSSNValue",
      "isDatavalidated": null
    },
	"txtDLNumberCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblDLNumberCoAError",
      "errorMessageMandatory": "Enter License Number",
      "errorMessageValid": "Enter valid License Number",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppDriversLicenseValue",
      "isDatavalidated": null
    },
	"txtHomePhoneNumberCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblDLNumberCoAError",
      "errorMessageMandatory": "Enter Home phone",
      "errorMessageValid": "Enter valid Home phone",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppHomePhoneValue",
      "isDatavalidated": null
    },
	"txtBusinessPhoneCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblDLNumberCoAError",
      "errorMessageMandatory": "Enter Business phone",
      "errorMessageValid": "Enter valid Business phone",
      "isMandatory": false,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppBusinessPhoneValue",
      "isDatavalidated": null
    },
	"txtCellPhoneCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblDLNumberCoAError",
      "errorMessageMandatory": "Enter Cell Phone",
      "errorMessageValid": "Enter valid Cell Phone",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppCellPhoneValue",
      "isDatavalidated": null
    },
    "txtAddressLine1CoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblAddressLine1CoAError",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPersonalInfoAddressLineValue",
      "isDatavalidated": null
    },
	"txtAddressLine2CoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblAddLine2CoAError",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPersonalInfoAddressLine2Value",
      "isDatavalidated": null
    },
    "lstAddress1CountryCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCountryCoAError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryCoAppCountryValue",
      "isDatavalidated": true
    },
    "lstAddress1StateCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblStateCoAError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryCoAppPersonalInfoStateValue",
      "isDatavalidated": true
    },
    "txtAddress1CityCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCityCoAError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPersonalInfoCityValue",
      "isDatavalidated": null
    },
    "txtAddress1ZipCodeCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblZipCodeCoAError",
      "errorMessageMandatory": "Enter ZIP Code",
      "errorMessageValid": "Enter valid ZIP Code",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppZipCodeValue",
      "isDatavalidated": null
    },
    "lstAddress10OccupyingPlaceCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblOccupyingPlaceError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"list",
      "reviewKey":"lblSummaryCoAppHousingValue",
      "isDatavalidated": true
    },
    "rbgYearsCoA": {
      "normalSkin": "sknRbgCoApplicantKA",
      "skin": "sknRbgError",
      "errorLabel": "lblYearsErrorCoA",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": true,
      "isValidated": null,
      "widgetType":"radio",
      "reviewKey":"lblReviewCoAppYearsAndMonthSpentValue",
      "isDatavalidated": true
    },
	"txtAddressLine1PreviousCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPrevAddressLine1CoAError",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPrevPersonalInfoAddressLine1Value",
      "isDatavalidated": null
    },
	"txtAddressLine2PreviousCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPrevAddressLine2CoAError",
      "errorMessageMandatory": "Enter Address",
      "errorMessageValid": "Enter valid Address",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPrevPersonalInfoAddressLine2Value",
      "isDatavalidated": null
    },
    "lstCountryPreviousCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCountryCoAError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "reviewKey":"lblSummaryCoAppPrevCountryValue",
      "isDatavalidated": true
    },
    "lstAddressStatePreviousCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblStateCoAError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "reviewKey":"lblSummaryPrevCoAppPersonalInfoStateValue",
      "isDatavalidated": true
    },
    "txtAddressCityPreviousCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblCityCoAError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPrevPersonalInfoCityValue",
      "isDatavalidated": null
    },
    "txtAddressZipCodePreviousCoA": {
      "normalSkin": "skntxtbxDetails0bbf1235271384a",
      "skin": "skntbxBordereb30173px",
      "errorLabel": "lblPrevZipCoAError",
      "errorMessageMandatory": "Enter ZIP Code",
      "errorMessageValid": "Enter valid ZIP Code",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"text",
      "reviewKey":"lblSummaryCoAppPrevZipCodeValue",
      "isDatavalidated": null
    },
    "lstAddressOccupyingPreviousCoA": {
      "normalSkin": "sknlstbx485c7513px",
      "skin": "sknLstBoxeb3017Bor3px",
      "errorLabel": "lblOccupyingPlaceError",
      "errorMessageMandatory": "Select atleast one option",
      "errorMessageValid": "Select atleast one option",
      "isMandatory": false,
      "isValidated": true,
      "widgetType":"list",
      "reviewKey":"lblSummaryCoAppPrevHousingValue",
      "isDatavalidated": true
    }
  },
  "Consent":{
    "flxAgreeCheckBox":{
      "normalSkin": "sknCursor",
      "skin": "sknCursor",
      "errorLabel": "lblTermsError",
      "isMandatory": false,
      "isValidated": false,
      "widgetType":"text"
    }
  }
};

kony.adminConsole.loans.applionsDataMap = [{
  "LoanType": "Persoanl Loan",
  "numberOfsections": "8",
  "section1": {
    "name": "YOUR_LOAN_GENERAL",
    "QuestionDefinitionIDs": {
      "applicationType": "QUESTION_COBORROWER",
      "loanAmount": "QUESTION_LOAN_AMOUNT",
      "loanPurpose": "QUESTION_LOAN_PURPOSE",
      "loanTerm": "QUESTION_LOAN_TERMS"
    },
    "QuerySectionQuestionIDs": {
      "applicationType": "PERSONAL_APPLICATION_CREDIT_REQUEST_COBORROWER",
      "loanAmount": "PERSONAL_APPLICATION_CREDIT_REQUEST_LOAN_AMOUNT",
      "loanPurpose": "PERSONAL_APPLICATION_CREDIT_REQUEST_LOAN_PURPOSE",
      "loanTerm": "PERSONAL_APPLICATION_LOAN_TERMS"
    },
    "QuestionResponse": {}
  },
  "section2": {
    "name": "PERSONAL_INFO_APPLICANT",
    "QuestionDefinitionIDs": {
      "fullName": "QUESTION_FULL_NAME",
      "suffix": "QUESTION_SUFFIX",
      "dateOfBirth": "QUESTION_DOB",
      "emailAddress": "QUESTION_EMAIL_ADDRESS",
      "ssn": "QUESTION_SSN",
      "DLNum": "QUESTION_DL",
      "cellPhoneNumber": "QUESTION_MOBILE_NUMBER",
      "homePhoneNumber": "QUESTION_HOME_NUMBER",
      "businessPhoneNumber": "QUESTION_OFFICE_NUMBER",
      "currentAddress": "QUESTION_CURR_ADD",
      "addressType": "QUESTION_CURR_ADD_TYPE",
      "addressDuration": "QUESTION_CURR_ADD_DURATION",
      "prevAddress": "QUESTION_PREV_ADD",
      "prevAddressType": "QUESTION_PREV_ADD_TYPE",
      "prevAddressDuration": "QUESTION_PREV_ADD_DURATION"
    },
    "QuerySectionQuestionIDs": {
      "fullName": "PERSONAL_APPLICATION_PERSONAL_INFO_FULL_NAME",
      "suffix": "PERSONAL_APPLICATION_PERSONAL_INFO_SUFFIX",
      "dateOfBirth": "PERSONAL_APPLICATION_PERSONAL_INFO_DOB",
      "emailAddress": "PERSONAL_APPLICATION_PERSONAL_INFO_EMAIL",
      "ssn": "PERSONAL_APPLICATION_PERSONAL_INFO_SSN",
      "DLNum": "PERSONAL_APPLICATION_PERSONAL_INFO_DL",
      "cellPhoneNumber": "PERSONAL_APPLICATION_PERSONAL_INFO_MOBILE_NUMBER",
      "homePhoneNumber": "PERSONAL_APPLICATION_PERSONAL_INFO_HOME_NUMBER",
      "businessPhoneNumber": "PERSONAL_APPLICATION_PERSONAL_INFO_OFFICE_NUMBER",
      "currentAddress": "PERSONAL_APPLICATION_PERSONAL_INFO_CURR_ADD",
      "addressType": "PERSONAL_APPLICATION_PERSONAL_INFO_CURR_ADD_TYPE",
      "addressDuration": "PERSONAL_APPLICATION_PERSONAL_INFO_CURR_ADD_DURATI",
      "prevAddress": "PERSONAL_APPLICATION_PERSONAL_INFO_PREV_ADD",
      "prevAddressType": "PERSONAL_APPLICATION_PERSONAL_INFO_PREV_ADD_TYPE",
      "prevAddressDuration": "PERSONAL_APPLICATION_PERSONAL_INFO_PREV_ADD_DURATI"
    },
    "QuestionResponse": {}
  },
  "section3": {
   "name": "INCOME_APPLICANT",
    "QuestionDefinitionIDs": {
      "currEmployerStatus": "QUESTION_EMPLOYMENT_STATUS",
      "currEmployerName": "QUESTION_CURRENT_EMPLOYER",
      "currEmployerDesignation": "QUESTION_CURRENT_DESIGNATION",
      "currEmployerStartDate": "QUESTION_EMPLOYER_START_DATE",
      "salary": "QUESTION_SALARY",
      "salaryType": "QUESTION_PAY_PERIOD",
      "currEmployerAddress": "QUESTION_EMPLOYER_ADDRESS",
      "isPrevEmployment" :"QUESTION_PREV_EMPLOYER_CHALLENGE",
      "prevEmployerName": "QUESTION_PREVIOUS_EMPLOYER",
      "prevEmployerStartDate": "QUESTION_PREV_EMP_START_DATE",
      "prevEmployerAddress": "QUESTION_PREV_EMPLOYER_ADDRESS",
      "otherIncomeSelect" :"QUESTION_OTHER_INCOME_SELECT",
      "alimony" :"QUESTION_ALIMONY_INCOME_INPUT",
      "annuity" :"QUESTION_ANNUITY_INCOME_INPUT",
      "interests":"QUESTION_INTERESTS_INCOME_INPUT",
      "pension" :"QUESTION_PENSION_INCOME_INPUT",
      "rentalIncome":"QUESTION_RENTAL_INCOME_INPUT",
      "SSIncome":"QUESTION_SOC_SECURITY_INCOME_INPUT",
      "otherIncome":"QUESTION_OTHER_INCOME_INPUT"

    },
    "QuerySectionQuestionIDs": {
      "currEmployerStatus": "PERSONAL_APPLICATION_INCOME_EMPLOYMENT_STATUS",
      "currEmployerName": "PERSONAL_APPLICATION_INCOME_CURR_EMPLOYER",
      "currEmployerDesignation": "PERSONAL_APPLICATION_INCOME_DESIGNATION",
      "currEmployerStartDate": "PERSONAL_APPLICATION_INCOME_START_DATE_EMPLOYER",
      "salary": "PERSONAL_APPLICATION_INCOME_SALARY",
      "salaryType": "PERSONAL_APPLICATION_INCOME_PAY_PERIOD",
      "currEmployerAddress": "PERSONAL_APPLICATION_INCOME_EMPLOYER_ADDRESS",
      "isPrevEmployment" : "PERSONAL_APPLICATION_INCOME_PREVIOUS_EMPLOYER_CHAL",
      "prevEmployerName": "PERSONAL_APPLICATION_INCOME_PREVIOUS_EMPLOYER",
      "prevEmployerStartDate": "PERSONAL_APPLICATION_INCOME_PREV_EMP_START_DATE",
      "prevEmployerAddress": "PERSONAL_APPLICATION_INCOME_PREV_EMPLOYER_ADDRESS",
      "otherIncomeSelect" :"PERSONAL_APP_OTHER_SOURCES_INCOME_SEL",
      "alimony" :"PERSONAL_APP_ALIMONY_INCOME",
      "annuity" :"PERSONAL_APP_ANNUITY_INCOME",
      "interests":"PERSONAL_APP_INTERESTS_INCOME",
      "pension" :"PERSONAL_APP_PENSION_INCOME",
      "rentalIncome":"PERSONAL_APP_RENTAL_INCOME",
      "SSIncome":"PERSONAL_APP_SOC_SECURITY_INCOME",
      "otherIncome":"PERSONAL_APP_OTHER_INCOME"
    },
    "QuestionResponse": {}
  },
  "section4": {
    "name": "CONSENT_APPLICANT",
    "QuestionDefinitionIDs": null,
    "QuerySectionQuestionIDs": null,
    "QuestionResponse": null
  },
  "section5": {
    "name": "PERSONAL_INFO_COAPPLICANT",
    "QuestionDefinitionIDs": {
      "fullName": "QUESTION_COAPPLICANT_FULL_NAME",
      "suffix": "QUESTION_COAPPLICANT_SUFFIX",
      "dateOfBirth": "QUESTION_COAPPLICANT_DOB",
      "emailAddress": "QUESTION_COAPPLICANT_EMAIL_ADDRESS",
      "ssn": "QUESTION_COAPPLICANT_SSN",
      "DLNum": "QUESTION_COAPPLICANT_DL",
      "cellPhoneNumber": "QUESTION_COAPPLICANT_MOBILE_NUMBER",
      "homePhoneNumber": "QUESTION_COAPPLICANT_HOME_NUMBER",
      "businessPhoneNumber": "QUESTION_COAPPLICANT_OFFICE_NUMBER",
      "currentAddress": "QUESTION_COAPPLICANT_CURR_ADD",
      "addressType": "QUESTION_COAPPLICANT_CURR_ADD_TYPE",
      "addressDuration": "QUESTION_COAPPLICANT_CURR_ADD_DURATION",
      "prevAddress": "QUESTION_COAPPLICANT_PREV_ADD",
      "prevAddressType": "QUESTION_COAPPLICANT_PREV_ADD_TYPE",
      "prevAddressDuration": "QUESTION_COAPPLICANT_PREV_ADD_DURATION"
    },
    "QuerySectionQuestionIDs": {
      "fullName": "PERSONAL_APP_PERSONAL_INFO_COAPP_FULL_NAME",
      "suffix": "PERSONAL_APP_PERSONAL_INFO_COAPP_SUFFIX",
      "dateOfBirth": "PERSONAL_APP_PERSONAL_INFO_COAPP_DOB",
      "emailAddress": "PERSONAL_APP_PERSONAL_INFO_COAPP_EMAIL",
      "ssn": "PERSONAL_APP_PERSONAL_INFO_COAPP_SSN",
      "DLNum": "PERSONAL_APP_PERSONAL_INFO_COAPP_DL",
      "cellPhoneNumber": "PERSONAL_APP_PERSONAL_INFO_COAPP_MOBILE_NUMBER",
      "homePhoneNumber": "PERSONAL_APP_PERSONAL_INFO_COAPP_HOME_NUMBER",
      "businessPhoneNumber": "PERSONAL_APP_PERSONAL_INFO_COAPP_OFFICE_NUMBER",
      "currentAddress": "PERSONAL_APP_PERSONAL_INFO_COAPP_CURR_ADD",
      "addressType": "PERSONAL_APP_PERSONAL_INFO_COAPP_CURR_ADD_TYPE",
      "addressDuration": "PERSONAL_APP_PERSONAL_INFO_COAPP_CURR_ADD_DURATI",
      "prevAddress": "PERSONAL_APP_PERSONAL_INFO_COAPP_PREV_ADD",
      "prevAddressType": "PERSONAL_APP_PERSONAL_INFO_COAPP_PREV_ADD_TYPE",
      "prevAddressDuration": "PERSONAL_APP_PERSONAL_INFO_COAPP_PREV_ADD_DURATI"
    },
    "QuestionResponse": {}
  },
  "section6": {
    "name": "INCOME_COAPPLICANT",
    "QuestionDefinitionIDs": {
      "currEmployerStatus": "QUESTION_COAPPLICANT_EMPLOYMENT_STATUS",
      "currEmployerName": "QUESTION_COAPPLICANT_CURRENT_EMPLOYER",
      "currEmployerDesignation": "QUESTION_COAPPLICANT_CURRENT_DESIGNATION",
      "currEmployerStartDate": "QUESTION_COAPPLICANT_EMPLOYER_START_DATE",
      "salary": "QUESTION_COAPPLICANT_SALARY",
      "salaryType": "QUESTION_COAPPLICANT_PAY_PERIOD",
      "currEmployerAddress": "QUESTION_COAPPLICANT_EMPLOYER_ADDRESS",
      "isPrevEmployment" :"QUESTION_COAPPLICANT_PREV_EMPLOYER_CHALLENGE",
      "prevEmployerName": "QUESTION_COAPPLICANT_PREVIOUS_EMPLOYER",
      "prevEmployerStartDate": "QUESTION_COAPPLICANT_PREV_EMP_START_DATE",
      "prevEmployerAddress": "QUESTION_COAPPLICANT_PREV_EMPLOYER_ADDRESS",
      "otherIncomeSelect" :"QUESTION_COAPPLICANT_OTHER_INCOME_SELECT",
      "alimony" :"QUESTION_COAPPLICANT_ALIMONY_INCOME_INPUT",
      "annuity" :"QUESTION_COAPPLICANT_ANNUITY_INCOME_INPUT",
      "interests":"QUESTION_COAPPLICANT_INTERESTS_INCOME_INPUT",
      "pension" :"QUESTION_COAPPLICANT_PENSION_INCOME_INPUT",
      "rentalIncome":"QUESTION_COAPPLICANT_RENTAL_INCOME_INPUT",
      "SSIncome":"QUESTION_COAPPLICANT_SOC_SECURITY_INCOME_INPUT",
      "otherIncome":"QUESTION_COAPPLICANT_OTHER_INCOME_INPUT"

    },
    "QuerySectionQuestionIDs": {
      "currEmployerStatus": "PERSONAL_APP_INCOME_COAPP_EMPLOYMENT_STATUS",
      "currEmployerName": "PERSONAL_APP_INCOME_COAPP_CURR_EMPLOYER",
      "currEmployerDesignation": "PERSONAL_APP_INCOME_COAPP_DESIGNATION",
      "currEmployerStartDate": "PERSONAL_APP_INCOME_COAPP_START_DATE_EMPLOYER",
      "salary": "PERSONAL_APP_INCOME_COAPP_SALARY",
      "salaryType": "PERSONAL_APP_INCOME_COAPP_PAY_PERIOD",
      "currEmployerAddress": "PERSONAL_APP_INCOME_COAPP_EMPLOYER_ADDRESS",
      "isPrevEmployment" : "PERSONAL_APP_INCOME_COAPP_PREVIOUS_EMPLOYER_CHAL",
      "prevEmployerName": "PERSONAL_APP_INCOME_COAPP_PREVIOUS_EMPLOYER",
      "prevEmployerStartDate": "PERSONAL_APP_INCOME_COAPP_PREV_EMP_START_DATE",
      "prevEmployerAddress": "PERSONAL_APP_INCOME_COAPP_PREV_EMPLOYER_ADDRESS",
      "otherIncomeSelect" :"PERSONAL_APP_COAPP_OTHER_SOURCES_INCOME_SEL",
      "alimony" :"PERSONAL_APP_COAPP_ALIMONY_INCOME",
      "annuity" :"PERSONAL_APP_COAPP_ANNUITY_INCOME",
      "interests":"PERSONAL_APP_COAPP_INTERESTS_INCOME",
      "pension" :"PERSONAL_APP_COAPP_PENSION_INCOME",
      "rentalIncome":"PERSONAL_APP_COAPP_RENTAL_INCOME",
      "SSIncome":"PERSONAL_APP_COAPP_SOC_SECURITY_INCOME",
      "otherIncome":"PERSONAL_APP_COAPP_OTHER_INCOME"

    },
    "QuestionResponse": {}
  },
  "section7": {
    "name": "CONSENT_COAPPLICANT",
    "QuestionDefinitionIDs": null,
    "QuerySectionQuestionIDs": null,
    "QuestionResponse": null
  },
  "section8": {
    "name": "SUMMARY",
    "QuestionDefinitionIDs": null,
    "QuerySectionQuestionIDs": null,
    "QuestionResponse": null
  }
}];

kony.adminConsole.loans.IncomeBasedQuestions = {
  "Select":{
    "flxPresentEmployement":false,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndStartDate":false,
    "flxTitle":false,
    "flxBussinessName":false,
    "flxPresentGincomeAndPeriod":false,
    "flxGrossIncome":false,
    "flxPeriod":false,
    "flxPresentEmployerAddressLine1":false,
    "flxPresentEmployerAddressLine2":false,
    "flxPresentCountryCityState":false,
    "flxPresentEmployerCountry":false,
    "flxPresentEmployerState":false,
    "flxPresentEmploymentCity":false,
    "flxPresentZipAndIsPrevEmployed":false,
    "flxPresentZipCode":false,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":false,
    "flxPreviousTitleAndStartDate":false,
    "flxPreviousDesignation":false,
    "flxPreviousIncomeAndPeriod":false,
    "flxPreviousIncome":false,
    "flxPreviousPayPeriod":false,
    "flxPreviousAddressOne":false,
    "flxPreviousAddressTwo":false,
    "flxPreviousCountryCityState":false,
    "flxPreviousCountry":false,
    "flxPreviousState":false,
    "flxPreviousCity":false,
    "flxPreviousZipCode":false,
    "flxFirstAddIncome":false
  },
  "Full Time":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":true,
    "flxPresentTitleAndStartDate":true,
    "flxTitle":true,
    "flxBussinessName":false,
    "flxPresentGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentCountryCityState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentZipAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndStartDate":true,
    "flxPreviousDesignation":true,
    "flxPreviousIncomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousCountryCityState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxFirstAddIncome":true
  },
  "Part Time":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":true,
    "flxPresentTitleAndStartDate":true,
    "flxTitle":true,
    "flxBussinessName":false,
    "flxPresentGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentCountryCityState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentZipAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndStartDate":true,
    "flxPreviousDesignation":true,
    "flxPreviousIncomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousCountryCityState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxFirstAddIncome":true
  },
  "Self Employed":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndStartDate":true,
    "flxTitle":false,
    "flxBussinessName":true,
    "flxPresentGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentCountryCityState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentZipAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndStartDate":true,
    "flxPreviousDesignation":true,
    "flxPreviousIncomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousCountryCityState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxFirstAddIncome":true
  },
  "Unemployed":{
    "flxPresentEmployement":false,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndStartDate":true,
    "flxTitle":false,
    "flxBussinessName":true,
    "flxPresentGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentCountryCityState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentZipAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndStartDate":true,
    "flxPreviousDesignation":true,
    "flxPreviousIncomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousCountryCityState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxFirstAddIncome":true
  },
  "Military":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndStartDate":true,
    "flxTitle":true,
    "flxBussinessName":false,
    "flxPresentGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":false,
    "flxPresentEmployerAddressLine1":false,
    "flxPresentEmployerAddressLine2":false,
    "flxPresentCountryCityState":false,
    "flxPresentEmployerCountry":false,
    "flxPresentEmployerState":false,
    "flxPresentEmploymentCity":false,
    "flxPresentZipAndIsPrevEmployed":false,
    "flxPresentZipCode":false,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndStartDate":true,
    "flxPreviousDesignation":true,
    "flxPreviousIncomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousCountryCityState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxFirstAddIncome":true
  },
  "Other":{
    "flxPresentEmployement":true,
    "flxDescription":true,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndStartDate":false,
    "flxTitle":false,
    "flxBussinessName":false,
    "flxPresentGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":false,
    "flxPresentEmployerAddressLine2":false,
    "flxPresentCountryCityState":false,
    "flxPresentEmployerCountry":false,
    "flxPresentEmployerState":false,
    "flxPresentEmploymentCity":false,
    "flxPresentZipAndIsPrevEmployed":false,
    "flxPresentZipCode":false,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndStartDate":true,
    "flxPreviousDesignation":true,
    "flxPreviousIncomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousCountryCityState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxFirstAddIncome":true
  }
};

kony.adminConsole.loans.firstAdditionalIncomeBasedQuestions = {
  "Select":{
    "flxFirstAddIncomeDetails":false,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":false,
    "flxFirstAddPayPeriod":false,
    "flxSecondAddIncome":false
  },
  "Alimony/Child support":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":true,
    "flxSecondAddIncome":true
  },
  "Annuity":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":true,
    "flxSecondAddIncome":true
  },
  "Interests/Dividends":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":false,
    "flxSecondAddIncome":true
  },
  "Pension":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":true,
    "flxSecondAddIncome":true
  },
  "Rental":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":false,
    "flxSecondAddIncome":true
  },
  "Social Security":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":false,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":false,
    "flxSecondAddIncome":true
  },
  "Other":{
    "flxFirstAddIncomeDetails":true,
    "flxFirstAddIncomeDescription":true,
    "flxFirstAddGrossIncome":true,
    "flxFirstAddPayPeriod":true,
    "flxSecondAddIncome":true,
  }
  
};

kony.adminConsole.loans.secondAdditionalIncomeBasedQuestions = {
  "Select":{
    "flxSecondAddIncomeDetails":false,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":false,
    "flxSecondAddPayPeriod":false
  },
  "Alimony/Child support":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":true
  },
  "Annuity":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":true
  },
  "Interests/Dividends":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":false
  },
  "Pension":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":true
  },
  "Rental":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":false
  },
  "Social Security":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":false,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":false
  },
  "Other":{
    "flxSecondAddIncomeDetails":true,
    "flxSecondAddIncomeDesc":true,
    "flxSecondAddGrossIncome":true,
    "flxSecondAddPayPeriod":true
  }
  
};

kony.adminConsole.loans.setQuestionResponseToDataMap = function(loanType,response){
  var scopeObj = this;
  var i = 0;
  var dataMapIndex = null;
  var queryResponseDataMap = {};
  for(i=0;i<kony.adminConsole.loans.applionsDataMap.length;i++){
    if(kony.adminConsole.loans.applionsDataMap[i].LoanType === loanType){
      queryResponseDataMap = kony.adminConsole.loans.applionsDataMap[i];
      dataMapIndex = i;
      break;
    }
  }
  for(i=1;i<=queryResponseDataMap.numberOfsections;i++){
    var sectionQuestionResponse = scopeObj.getSectionQuestionResponse(queryResponseDataMap["section"+i].name, response);
    kony.adminConsole.loans.applionsDataMap[dataMapIndex]["section"+i].QuestionResponse = sectionQuestionResponse;
  }
};

kony.adminConsole.loans.getSectionQuestionResponse = function(sectionName,response){
  var scopeObj = this;
  var i = 0;
  var sectionQuestionResponse = [];
  for(i=0;i<response.length;i++){
    if(response[i].QuerySection_id === sectionName){
      sectionQuestionResponse.push(response[i]);
    }
  }
  var questionResponseJson = scopeObj.formatQuestionresponse(sectionQuestionResponse);
  return questionResponseJson;
};

kony.adminConsole.loans.formatQuestionresponse = function(questionResponse){
  var scopeObj = this;
  var i = 0;
  var questionResponseJson = {};
  for(i=0;i<questionResponse.length;i++){
    questionResponseJson[questionResponse[i].QuestionDefinition_id] =  questionResponse[i];
  }
  return questionResponseJson;
};

kony.adminConsole.loans.IncomeBasedQuestionsCoA = {
  "Select":{
    "flxPresentEmployementCoA":false,
    "flxDescriptionCoA":false,
    "flxPresentNameOfTheEmployerCoA":false,
    "flxPresentTitleAndStartDateCoA":false,
    "flxTitleCoA":false,
    "flxBussinessNameCoA":false,
    "flxPresentGincomeAndPeriodCoA":false,
    "flxGrossIncomeCoA":false,
    "flxPeriodCoA":false,
    "flxPresentEmployerAddressLine1CoA":false,
    "flxPresentEmployerAddressLine2CoA":false,
    "flxPresentCountryCityStateCoA":false,
    "flxPresentEmployerCountryCoA":false,
    "flxPresentEmployerStateCoA":false,
    "flxPresentEmploymentCityCoA":false,
    "flxPresentZipAndIsPrevEmployedCoA":false,
    "flxPresentZipCodeCoA":false,
    "flxIsPreviouslyEmployedCoA":false,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":false,
    "flxPreviousTitleAndStartDateCoA":false,
    "flxPreviousDesignationCoA":false,
    "flxPreviousIncomeAndPeriodCoA":false,
    "flxPreviousIncomeCoA":false,
    "flxPreviousPayPeriodCoA":false,
    "flxPreviousAddressOneCoA":false,
    "flxPreviousAddressTwoCoA":false,
    "flxPreviousCountryCityStateCoA":false,
    "flxPreviousCountryCoA":false,
    "flxPreviousStateCoA":false,
    "flxPreviousCityCoA":false,
    "flxPreviousZipCodeCoA":false,
    "flxFirstAddIncomeCoA":false
  },
  "Full Time":{
    "flxPresentEmployementCoA":true,
    "flxDescriptionCoA":false,
    "flxPresentNameOfTheEmployerCoA":true,
    "flxPresentTitleAndStartDateCoA":true,
    "flxTitleCoA":true,
    "flxBussinessNameCoA":false,
    "flxPresentGincomeAndPeriodCoA":true,
    "flxGrossIncomeCoA":true,
    "flxPeriodCoA":true,
    "flxPresentEmployerAddressLine1CoA":true,
    "flxPresentEmployerAddressLine2CoA":true,
    "flxPresentCountryCityStateCoA":true,
    "flxPresentEmployerCountryCoA":true,
    "flxPresentEmployerStateCoA":true,
    "flxPresentEmploymentCityCoA":true,
    "flxPresentZipAndIsPrevEmployedCoA":true,
    "flxPresentZipCodeCoA":true,
    "flxIsPreviouslyEmployedCoA":true,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":true,
    "flxPreviousTitleAndStartDateCoA":true,
    "flxPreviousDesignationCoA":true,
    "flxPreviousIncomeAndPeriodCoA":true,
    "flxPreviousIncomeCoA":true,
    "flxPreviousPayPeriodCoA":true,
    "flxPreviousAddressOneCoA":true,
    "flxPreviousAddressTwoCoA":true,
    "flxPreviousCountryCityStateCoA":true,
    "flxPreviousCountryCoA":true,
    "flxPreviousStateCoA":true,
    "flxPreviousCityCoA":true,
    "flxPreviousZipCodeCoA":true,
    "flxFirstAddIncomeCoA":true
  },
  "Part Time":{
    "flxPresentEmployementCoA":true,
    "flxDescriptionCoA":false,
    "flxPresentNameOfTheEmployerCoA":true,
    "flxPresentTitleAndStartDateCoA":true,
    "flxTitleCoA":true,
    "flxBussinessNameCoA":false,
    "flxPresentGincomeAndPeriodCoA":true,
    "flxGrossIncomeCoA":true,
    "flxPeriodCoA":true,
    "flxPresentEmployerAddressLine1CoA":true,
    "flxPresentEmployerAddressLine2CoA":true,
    "flxPresentCountryCityStateCoA":true,
    "flxPresentEmployerCountryCoA":true,
    "flxPresentEmployerStateCoA":true,
    "flxPresentEmploymentCityCoA":true,
    "flxPresentZipAndIsPrevEmployedCoA":true,
    "flxPresentZipCodeCoA":true,
    "flxIsPreviouslyEmployedCoA":true,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":true,
    "flxPreviousTitleAndStartDateCoA":true,
    "flxPreviousDesignationCoA":true,
    "flxPreviousIncomeAndPeriodCoA":true,
    "flxPreviousIncomeCoA":true,
    "flxPreviousPayPeriodCoA":true,
    "flxPreviousAddressOneCoA":true,
    "flxPreviousAddressTwoCoA":true,
    "flxPreviousCountryCityStateCoA":true,
    "flxPreviousCountryCoA":true,
    "flxPreviousStateCoA":true,
    "flxPreviousCityCoA":true,
    "flxPreviousZipCodeCoA":true,
    "flxFirstAddIncomeCoA":true
  },
  "Self Employed":{
    "flxPresentEmployementCoA":true,
    "flxDescriptionCoA":false,
    "flxPresentNameOfTheEmployerCoA":false,
    "flxPresentTitleAndStartDateCoA":true,
    "flxTitleCoA":false,
    "flxBussinessNameCoA":true,
    "flxPresentGincomeAndPeriodCoA":true,
    "flxGrossIncomeCoA":true,
    "flxPeriodCoA":true,
    "flxPresentEmployerAddressLine1CoA":true,
    "flxPresentEmployerAddressLine2CoA":true,
    "flxPresentCountryCityStateCoA":true,
    "flxPresentEmployerCountryCoA":true,
    "flxPresentEmployerStateCoA":true,
    "flxPresentEmploymentCityCoA":true,
    "flxPresentZipAndIsPrevEmployedCoA":true,
    "flxPresentZipCodeCoA":true,
    "flxIsPreviouslyEmployedCoA":false,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":true,
    "flxPreviousTitleAndStartDateCoA":true,
    "flxPreviousDesignationCoA":true,
    "flxPreviousIncomeAndPeriodCoA":true,
    "flxPreviousIncomeCoA":true,
    "flxPreviousPayPeriodCoA":true,
    "flxPreviousAddressOneCoA":true,
    "flxPreviousAddressTwoCoA":true,
    "flxPreviousCountryCityStateCoA":true,
    "flxPreviousCountryCoA":true,
    "flxPreviousStateCoA":true,
    "flxPreviousCityCoA":true,
    "flxPreviousZipCodeCoA":true,
    "flxFirstAddIncomeCoA":true
  },
  "Unemployed":{
    "flxPresentEmployementCoA":false,
    "flxDescriptionCoA":false,
    "flxPresentNameOfTheEmployerCoA":false,
    "flxPresentTitleAndStartDateCoA":true,
    "flxTitleCoA":false,
    "flxBussinessNameCoA":true,
    "flxPresentGincomeAndPeriodCoA":true,
    "flxGrossIncomeCoA":true,
    "flxPeriodCoA":true,
    "flxPresentEmployerAddressLine1CoA":true,
    "flxPresentEmployerAddressLine2CoA":true,
    "flxPresentCountryCityStateCoA":true,
    "flxPresentEmployerCountryCoA":true,
    "flxPresentEmployerStateCoA":true,
    "flxPresentEmploymentCityCoA":true,
    "flxPresentZipAndIsPrevEmployedCoA":true,
    "flxPresentZipCodeCoA":true,
    "flxIsPreviouslyEmployedCoA":false,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":true,
    "flxPreviousTitleAndStartDateCoA":true,
    "flxPreviousDesignationCoA":true,
    "flxPreviousIncomeAndPeriodCoA":true,
    "flxPreviousIncomeCoA":true,
    "flxPreviousPayPeriodCoA":true,
    "flxPreviousAddressOneCoA":true,
    "flxPreviousAddressTwoCoA":true,
    "flxPreviousCountryCityStateCoA":true,
    "flxPreviousCountryCoA":true,
    "flxPreviousStateCoA":true,
    "flxPreviousCityCoA":true,
    "flxPreviousZipCodeCoA":true,
    "flxFirstAddIncomeCoA":true
  },
  "Military":{
    "flxPresentEmployementCoA":true,
    "flxDescriptionCoA":false,
    "flxPresentNameOfTheEmployerCoA":false,
    "flxPresentTitleAndStartDateCoA":true,
    "flxTitleCoA":true,
    "flxBussinessNameCoA":false,
    "flxPresentGincomeAndPeriodCoA":true,
    "flxGrossIncomeCoA":true,
    "flxPeriodCoA":false,
    "flxPresentEmployerAddressLine1CoA":false,
    "flxPresentEmployerAddressLine2CoA":false,
    "flxPresentCountryCityStateCoA":false,
    "flxPresentEmployerCountryCoA":false,
    "flxPresentEmployerStateCoA":false,
    "flxPresentEmploymentCityCoA":false,
    "flxPresentZipAndIsPrevEmployedCoA":false,
    "flxPresentZipCodeCoA":false,
    "flxIsPreviouslyEmployedCoA":false,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":true,
    "flxPreviousTitleAndStartDateCoA":true,
    "flxPreviousDesignationCoA":true,
    "flxPreviousIncomeAndPeriodCoA":true,
    "flxPreviousIncomeCoA":true,
    "flxPreviousPayPeriodCoA":true,
    "flxPreviousAddressOneCoA":true,
    "flxPreviousAddressTwoCoA":true,
    "flxPreviousCountryCityStateCoA":true,
    "flxPreviousCountryCoA":true,
    "flxPreviousStateCoA":true,
    "flxPreviousCityCoA":true,
    "flxPreviousZipCodeCoA":true,
    "flxFirstAddIncomeCoA":true
  },
  "Other":{
    "flxPresentEmployementCoA":true,
    "flxDescriptionCoA":true,
    "flxPresentNameOfTheEmployerCoA":false,
    "flxPresentTitleAndStartDateCoA":false,
    "flxTitleCoA":false,
    "flxBussinessNameCoA":false,
    "flxPresentGincomeAndPeriodCoA":true,
    "flxGrossIncomeCoA":true,
    "flxPeriodCoA":true,
    "flxPresentEmployerAddressLine1CoA":false,
    "flxPresentEmployerAddressLine2CoA":false,
    "flxPresentCountryCityStateCoA":false,
    "flxPresentEmployerCountryCoA":false,
    "flxPresentEmployerStateCoA":false,
    "flxPresentEmploymentCityCoA":false,
    "flxPresentZipAndIsPrevEmployedCoA":false,
    "flxPresentZipCodeCoA":false,
    "flxIsPreviouslyEmployedCoA":false,
    "flxPreviousEmployementCoA":false,
    "flxPreviousEmployerNameCoA":true,
    "flxPreviousTitleAndStartDateCoA":true,
    "flxPreviousDesignationCoA":true,
    "flxPreviousIncomeAndPeriodCoA":true,
    "flxPreviousIncomeCoA":true,
    "flxPreviousPayPeriodCoA":true,
    "flxPreviousAddressOneCoA":true,
    "flxPreviousAddressTwoCoA":true,
    "flxPreviousCountryCityStateCoA":true,
    "flxPreviousCountryCoA":true,
    "flxPreviousStateCoA":true,
    "flxPreviousCityCoA":true,
    "flxPreviousZipCodeCoA":true,
    "flxFirstAddIncomeCoA":true
  }
};

kony.adminConsole.loans.firstAdditionalIncomeBasedQuestionsCoA = {
  "Select":{
    "flxFirstAddIncomeDetailsCoA":false,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":false,
    "flxFirstAddPayPeriodCoA":false,
    "flxSecondAddIncomeCoA":false
  },
  "Alimony/Child support":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":true,
    "flxSecondAddIncomeCoA":true
  },
  "Annuity":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":true,
    "flxSecondAddIncomeCoA":true
  },
  "Interests/Dividends":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":false,
    "flxSecondAddIncomeCoA":true
  },
  "Pension":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":true,
    "flxSecondAddIncomeCoA":true
  },
  "Rental":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":false,
    "flxSecondAddIncomeCoA":true
  },
  "Social Security":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":false,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":false,
    "flxSecondAddIncomeCoA":true
  },
  "Other":{
    "flxFirstAddIncomeDetailsCoA":true,
    "flxFirstAddIncomeDescriptionCoA":true,
    "flxFirstAddGrossIncomeCoA":true,
    "flxFirstAddPayPeriodCoA":true,
    "flxSecondAddIncomeCoA":true,
  }
  
};

kony.adminConsole.loans.secondAdditionalIncomeBasedQuestionsCoA = {
  "Select":{
    "flxSecondAddIncomeDetailsCoA":false,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":false,
    "flxSecondAddPayPeriodCoA":false
  },
  "Alimony/Child support":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":true
  },
  "Annuity":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":true
  },
  "Interests/Dividends":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":false
  },
  "Pension":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":true
  },
  "Rental":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":false
  },
  "Social Security":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":false,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":false
  },
  "Other":{
    "flxSecondAddIncomeDetailsCoA":true,
    "flxSecondAddIncomeDescCoA":true,
    "flxSecondAddGrossIncomeCoA":true,
    "flxSecondAddPayPeriodCoA":true
  }
  
};

kony.adminConsole.loans.IncomeBasedQuestionsCC = {
  "Select":{
    "flxPresentEmployement":false,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndEmpName":false,
    "flxTitle":false,
    "flxBussinessName":false,
    "flxPresentDateGincomeAndPeriod":false,
    "flxGrossIncome":false,
    "flxPeriod":false,
    "flxPresentEmployerAddressLine1":false,
    "flxPresentEmployerAddressLine2":false,
    "flxPresentZipCountryState":false,
    "flxPresentEmployerCountry":false,
    "flxPresentEmployerState":false,
    "flxPresentEmploymentCity":false,
    "flxPresentCityAndIsPrevEmployed":false,
    "flxPresentZipCode":false,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":false,
    "flxPreviousTitleAndEmpName":false,
    "flxPreviousDesignation":false,
    "flxPreviousDateGincomeAndPeriod":false,
    "flxPreviousIncome":false,
    "flxPreviousPayPeriod":false,
    "flxPreviousAddressOne":false,
    "flxPreviousAddressTwo":false,
    "flxPreviousZipCountryState":false,
    "flxPreviousCountry":false,
    "flxPreviousState":false,
    "flxPreviousCity":false,
    "flxPreviousZipCode":false,
    "flxAdditionalIncomeSource":false,
    "flxProvideIncomeIfAny":false,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  },
  "EMP_TYPE_1":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":true,
    "flxPresentTitleAndEmpName":true,
    "flxTitle":true,
    "flxBussinessName":false,
    "flxPresentDateGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentZipCountryState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentCityAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":true,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndEmpName":true,
    "flxPreviousDesignation":true,
    "flxPreviousDateGincomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousZipCountryState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxAdditionalIncomeSource":true,
    "flxProvideIncomeIfAny":true,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  },
  "EMP_TYPE_2":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":true,
    "flxPresentTitleAndEmpName":true,
    "flxTitle":true,
    "flxBussinessName":false,
    "flxPresentDateGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentZipCountryState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentCityAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":true,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndEmpName":true,
    "flxPreviousDesignation":true,
    "flxPreviousDateGincomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousZipCountryState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxAdditionalIncomeSource":true,
    "flxProvideIncomeIfAny":true,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  },
  "EMP_TYPE_3":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndEmpName":true,
    "flxTitle":false,
    "flxBussinessName":true,
    "flxPresentDateGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentZipCountryState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentCityAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndEmpName":true,
    "flxPreviousDesignation":true,
    "flxPreviousDateGincomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousZipCountryState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxAdditionalIncomeSource":true,
    "flxProvideIncomeIfAny":true,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  },
  "EMP_TYPE_5":{
    "flxPresentEmployement":false,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndEmpName":true,
    "flxTitle":false,
    "flxBussinessName":true,
    "flxPresentDateGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":true,
    "flxPresentEmployerAddressLine2":true,
    "flxPresentZipCountryState":true,
    "flxPresentEmployerCountry":true,
    "flxPresentEmployerState":true,
    "flxPresentEmploymentCity":true,
    "flxPresentCityAndIsPrevEmployed":true,
    "flxPresentZipCode":true,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndEmpName":true,
    "flxPreviousDesignation":true,
    "flxPreviousDateGincomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousZipCountryState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxAdditionalIncomeSource":true,
    "flxProvideIncomeIfAny":true,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  },
  "EMP_TYPE_4":{
    "flxPresentEmployement":true,
    "flxDescription":false,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndEmpName":true,
    "flxTitle":true,
    "flxBussinessName":false,
    "flxPresentDateGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":false,
    "flxPresentEmployerAddressLine1":false,
    "flxPresentEmployerAddressLine2":false,
    "flxPresentZipCountryState":false,
    "flxPresentEmployerCountry":false,
    "flxPresentEmployerState":false,
    "flxPresentEmploymentCity":false,
    "flxPresentCityAndIsPrevEmployed":false,
    "flxPresentZipCode":false,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndEmpName":true,
    "flxPreviousDesignation":true,
    "flxPreviousDateGincomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousZipCountryState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxAdditionalIncomeSource":true,
    "flxProvideIncomeIfAny":true,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  },
  "EMP_TYPE_6":{
    "flxPresentEmployement":true,
    "flxDescription":true,
    "flxPresentNameOfTheEmployer":false,
    "flxPresentTitleAndEmpName":false,
    "flxTitle":false,
    "flxBussinessName":false,
    "flxPresentDateGincomeAndPeriod":true,
    "flxGrossIncome":true,
    "flxPeriod":true,
    "flxPresentEmployerAddressLine1":false,
    "flxPresentEmployerAddressLine2":false,
    "flxPresentZipCountryState":false,
    "flxPresentEmployerCountry":false,
    "flxPresentEmployerState":false,
    "flxPresentEmploymentCity":false,
    "flxPresentCityAndIsPrevEmployed":false,
    "flxPresentZipCode":false,
    "flxIsPreviouslyEmployed":false,
    "flxPreviousEmployement":false,
    "flxPreviousEmployerName":true,
    "flxPreviousTitleAndEmpName":true,
    "flxPreviousDesignation":true,
    "flxPreviousDateGincomeAndPeriod":true,
    "flxPreviousIncome":true,
    "flxPreviousPayPeriod":true,
    "flxPreviousAddressOne":true,
    "flxPreviousAddressTwo":true,
    "flxPreviousZipCountryState":true,
    "flxPreviousCountry":true,
    "flxPreviousState":true,
    "flxPreviousCity":true,
    "flxPreviousZipCode":true,
    "flxAdditionalIncomeSource":true,
    "flxProvideIncomeIfAny":true,
    "flxAddIncomeFirst":false,
    "flxOtherIncomeSource":false,
    "flxAddIncomeSecond":false,
    "flxAddIncomeThird":false,
    "flxAddIncomeFourth":false,
    "flxAddIncomeFive":false,
    "flxAddIncomeSix":false,
    "flxAddIncomeSeven":false
  }
};
